app.backend.api-base-url=http://localhost:8081/api/
app.feature.cart-enabled=true
app.feature.promotions-enabled=true
app.feature.orders-enabled=true
app.feature.payment-enabled=true
app.feature.chat-enabled=true
