-- PostgreSQL conversion sourced from dbBanLinhKienPC.sql
-- Target app compatibility: BE (Spring Boot) currently uses snake_case table names.

SET client_encoding = 'UTF8';

DROP TRIGGER IF EXISTS trg_tu_dong_het_han_otp_cu ON otp_log;
DROP TRIGGER IF EXISTS trg_cap_nhat_ton_kho_nhap_hang ON chi_tiet_phieu_nhap;
DROP TRIGGER IF EXISTS trg_cap_nhat_ton_kho_ban_hang ON chi_tiet_don_hang;
DROP TRIGGER IF EXISTS trg_tinh_tong_tien_don_hang ON chi_tiet_don_hang;

DROP FUNCTION IF EXISTS fn_tu_dong_het_han_otp_cu();
DROP FUNCTION IF EXISTS fn_cap_nhat_ton_kho_nhap_hang();
DROP FUNCTION IF EXISTS fn_cap_nhat_ton_kho_ban_hang();
DROP FUNCTION IF EXISTS fn_tinh_tong_tien_don_hang();
DROP FUNCTION IF EXISTS fn_tinh_luong_nhan_vien(INTEGER, INTEGER);

DROP PROCEDURE IF EXISTS sp_dang_ky_khach_hang(VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR);
DROP PROCEDURE IF EXISTS sp_them_vao_gio_hang(INTEGER, INTEGER, INTEGER);
DROP PROCEDURE IF EXISTS sp_tao_don_hang(INTEGER, VARCHAR, VARCHAR, VARCHAR, VARCHAR, VARCHAR, INTEGER);

DROP TABLE IF EXISTS chi_tiet_phien_chat CASCADE;
DROP TABLE IF EXISTS phien_chat CASCADE;
DROP TABLE IF EXISTS nhat_ky_hoat_dong CASCADE;
DROP TABLE IF EXISTS giao_dich_thanh_toan CASCADE;
DROP TABLE IF EXISTS chi_tiet_don_hang CASCADE;
DROP TABLE IF EXISTS don_hang CASCADE;
DROP TABLE IF EXISTS chi_tiet_gio_hang CASCADE;
DROP TABLE IF EXISTS gio_hang CASCADE;
DROP TABLE IF EXISTS khuyen_mai_khach_hang CASCADE;
DROP TABLE IF EXISTS khuyen_mai CASCADE;
DROP TABLE IF EXISTS chi_tiet_phieu_nhap CASCADE;
DROP TABLE IF EXISTS phieu_nhap CASCADE;
DROP TABLE IF EXISTS thong_so_ky_thuat CASCADE;
DROP TABLE IF EXISTS hinh_anh_san_pham CASCADE;
DROP TABLE IF EXISTS san_pham CASCADE;
DROP TABLE IF EXISTS so_dia_chi CASCADE;
DROP TABLE IF EXISTS khach_hang CASCADE;
DROP TABLE IF EXISTS nhan_vien CASCADE;
DROP TABLE IF EXISTS otp_log CASCADE;
DROP TABLE IF EXISTS tai_khoan CASCADE;
DROP TABLE IF EXISTS danh_muc CASCADE;
DROP TABLE IF EXISTS vai_tro CASCADE;

CREATE TABLE vai_tro (
    ma_vai_tro INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_vai_tro VARCHAR(50) NOT NULL UNIQUE,
    mo_ta VARCHAR(255)
);

CREATE TABLE danh_muc (
    ma_danh_muc INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_danh_muc VARCHAR(100) NOT NULL,
    mo_ta VARCHAR(255),
    ma_danh_muc_cha INTEGER,
    CONSTRAINT fk_danh_muc_cha FOREIGN KEY (ma_danh_muc_cha) REFERENCES danh_muc (ma_danh_muc)
);

CREATE TABLE tai_khoan (
    ma_tai_khoan INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_dang_nhap VARCHAR(50) NOT NULL UNIQUE,
    mat_khau_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    anh_dai_dien TEXT,
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'Active',
    ngay_tao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_tai_khoan_trang_thai CHECK (trang_thai IN ('Active', 'Banned', 'Locked'))
);

CREATE TABLE otp_log (
    ma_log INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    ma_otp VARCHAR(10) NOT NULL,
    thoi_gian_tao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    thoi_gian_het_han TIMESTAMP NOT NULL,
    trang_thai VARCHAR(20) NOT NULL DEFAULT 'ConHan',
    CONSTRAINT ck_otp_log_trang_thai CHECK (trang_thai IN ('ConHan', 'HetHan', 'DaSuDung'))
);

CREATE TABLE nhan_vien (
    ma_nhan_vien INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_code_nhan_vien VARCHAR(20) NOT NULL UNIQUE,
    ho_ten VARCHAR(100) NOT NULL,
    so_dien_thoai VARCHAR(15),
    ma_tai_khoan INTEGER NOT NULL UNIQUE,
    ma_vai_tro INTEGER NOT NULL,
    CONSTRAINT fk_nhan_vien_tai_khoan FOREIGN KEY (ma_tai_khoan) REFERENCES tai_khoan (ma_tai_khoan),
    CONSTRAINT fk_nhan_vien_vai_tro FOREIGN KEY (ma_vai_tro) REFERENCES vai_tro (ma_vai_tro)
);

CREATE TABLE khach_hang (
    ma_khach_hang INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ho_ten VARCHAR(100) NOT NULL,
    so_dien_thoai VARCHAR(15) NOT NULL,
    email VARCHAR(100),
    ma_tai_khoan INTEGER UNIQUE,
    CONSTRAINT fk_khach_hang_tai_khoan FOREIGN KEY (ma_tai_khoan) REFERENCES tai_khoan (ma_tai_khoan)
);

CREATE TABLE so_dia_chi (
    ma_so_dia_chi INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_khach_hang INTEGER NOT NULL,
    ten_nguoi_nhan VARCHAR(100) NOT NULL DEFAULT '',
    so_dien_thoai VARCHAR(15) NOT NULL DEFAULT '',
    dia_chi_cu_the VARCHAR(255) NOT NULL,
    phuong_xa_id VARCHAR(20),
    quan_huyen_id VARCHAR(20),
    tinh_thanh_id VARCHAR(20),
    mac_dinh BOOLEAN NOT NULL DEFAULT FALSE,
    ten_tinh_thanh VARCHAR(100),
    ten_quan_huyen VARCHAR(100),
    ten_phuong_xa VARCHAR(100),
    CONSTRAINT fk_so_dia_chi_khach_hang FOREIGN KEY (ma_khach_hang) REFERENCES khach_hang (ma_khach_hang) ON DELETE CASCADE
);

CREATE TABLE san_pham (
    ma_san_pham INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_san_pham VARCHAR(255) NOT NULL,
    gia_ban NUMERIC(18, 2) NOT NULL DEFAULT 0,
    gia_khuyen_mai NUMERIC(18, 2) DEFAULT 0,
    so_luong_ton INTEGER NOT NULL DEFAULT 0,
    mo_ta TEXT,
    ma_danh_muc INTEGER NOT NULL,
    trang_thai BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_san_pham_danh_muc FOREIGN KEY (ma_danh_muc) REFERENCES danh_muc (ma_danh_muc),
    CONSTRAINT ck_san_pham_gia_ban CHECK (gia_ban >= 0),
    CONSTRAINT ck_san_pham_so_luong_ton CHECK (so_luong_ton >= 0)
);

CREATE TABLE hinh_anh_san_pham (
    ma_hinh_anh INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_san_pham INTEGER NOT NULL,
    url_hinh_anh TEXT NOT NULL,
    public_id VARCHAR(255),
    la_anh_dai_dien BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_hinh_anh_san_pham FOREIGN KEY (ma_san_pham) REFERENCES san_pham (ma_san_pham) ON DELETE CASCADE
);

CREATE TABLE thong_so_ky_thuat (
    ma_thong_so INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_san_pham INTEGER NOT NULL,
    ten_thong_so VARCHAR(100) NOT NULL,
    gia_tri VARCHAR(255) NOT NULL,
    CONSTRAINT fk_thong_so_ky_thuat_san_pham FOREIGN KEY (ma_san_pham) REFERENCES san_pham (ma_san_pham) ON DELETE CASCADE
);

CREATE TABLE phieu_nhap (
    ma_phieu_nhap INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_code_phieu VARCHAR(50) NOT NULL UNIQUE,
    ngay_nhap TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tong_tien_nhap NUMERIC(18, 2) NOT NULL DEFAULT 0,
    ma_nhan_vien_nhap INTEGER NOT NULL,
    ghi_chu TEXT,
    CONSTRAINT fk_phieu_nhap_nhan_vien FOREIGN KEY (ma_nhan_vien_nhap) REFERENCES nhan_vien (ma_nhan_vien)
);

CREATE TABLE chi_tiet_phieu_nhap (
    ma_chi_tiet_phieu_nhap INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_phieu_nhap INTEGER NOT NULL,
    ma_san_pham INTEGER NOT NULL,
    so_luong_nhap INTEGER NOT NULL,
    gia_nhap NUMERIC(18, 2) NOT NULL,
    CONSTRAINT fk_chi_tiet_phieu_nhap_phieu_nhap FOREIGN KEY (ma_phieu_nhap) REFERENCES phieu_nhap (ma_phieu_nhap) ON DELETE CASCADE,
    CONSTRAINT fk_chi_tiet_phieu_nhap_san_pham FOREIGN KEY (ma_san_pham) REFERENCES san_pham (ma_san_pham),
    CONSTRAINT ck_chi_tiet_phieu_nhap_so_luong CHECK (so_luong_nhap > 0),
    CONSTRAINT ck_chi_tiet_phieu_nhap_gia_nhap CHECK (gia_nhap >= 0)
);

CREATE TABLE khuyen_mai (
    ma_khuyen_mai INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_code_km VARCHAR(50) NOT NULL UNIQUE,
    ten_chuong_trinh VARCHAR(255) NOT NULL,
    gia_tri_giam NUMERIC(18, 2) NOT NULL,
    loai_giam VARCHAR(20) NOT NULL,
    don_hang_toi_thieu NUMERIC(18, 2) NOT NULL DEFAULT 0,
    giam_toi_da NUMERIC(18, 2),
    ngay_bat_dau TIMESTAMP NOT NULL,
    ngay_ket_thuc TIMESTAMP NOT NULL,
    so_luong_con_lai INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ck_khuyen_mai_loai_giam CHECK (loai_giam IN ('DIRECT', 'PERCENT')),
    CONSTRAINT ck_khuyen_mai_ngay CHECK (ngay_ket_thuc >= ngay_bat_dau)
);

CREATE TABLE khuyen_mai_khach_hang (
    ma_kmkh INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_khuyen_mai INTEGER NOT NULL,
    ma_khach_hang INTEGER NOT NULL,
    da_su_dung BOOLEAN NOT NULL DEFAULT FALSE,
    ngay_thu_thap TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_khuyen_mai_khach_hang_khuyen_mai FOREIGN KEY (ma_khuyen_mai) REFERENCES khuyen_mai (ma_khuyen_mai) ON DELETE CASCADE,
    CONSTRAINT fk_khuyen_mai_khach_hang_khach_hang FOREIGN KEY (ma_khach_hang) REFERENCES khach_hang (ma_khach_hang) ON DELETE CASCADE
);

CREATE TABLE gio_hang (
    ma_gio_hang INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_khach_hang INTEGER NOT NULL UNIQUE,
    ngay_cap_nhat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_gio_hang_khach_hang FOREIGN KEY (ma_khach_hang) REFERENCES khach_hang (ma_khach_hang)
);

CREATE TABLE chi_tiet_gio_hang (
    ma_chi_tiet_gio_hang INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_gio_hang INTEGER NOT NULL,
    ma_san_pham INTEGER NOT NULL,
    so_luong INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_chi_tiet_gio_hang_gio_hang FOREIGN KEY (ma_gio_hang) REFERENCES gio_hang (ma_gio_hang) ON DELETE CASCADE,
    CONSTRAINT fk_chi_tiet_gio_hang_san_pham FOREIGN KEY (ma_san_pham) REFERENCES san_pham (ma_san_pham),
    CONSTRAINT ck_chi_tiet_gio_hang_so_luong CHECK (so_luong > 0)
);

CREATE TABLE don_hang (
    ma_don_hang INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_code_don_hang VARCHAR(50) NOT NULL UNIQUE,
    ma_khach_hang INTEGER NOT NULL,
    ma_nhan_vien_duyet INTEGER,
    ngay_dat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tong_tien NUMERIC(18, 2) NOT NULL DEFAULT 0,
    trang_thai VARCHAR(50) NOT NULL DEFAULT 'ChoXacNhan',
    phuong_thuc_thanh_toan VARCHAR(50) NOT NULL DEFAULT 'COD',
    dia_chi_giao_hang VARCHAR(255) NOT NULL,
    so_dien_thoai_giao VARCHAR(15) NOT NULL,
    nguoi_nhan VARCHAR(100) NOT NULL,
    phi_van_chuyen NUMERIC(18, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_don_hang_khach_hang FOREIGN KEY (ma_khach_hang) REFERENCES khach_hang (ma_khach_hang),
    CONSTRAINT fk_don_hang_nhan_vien FOREIGN KEY (ma_nhan_vien_duyet) REFERENCES nhan_vien (ma_nhan_vien)
);

CREATE TABLE chi_tiet_don_hang (
    ma_chi_tiet_don_hang INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_don_hang INTEGER NOT NULL,
    ma_san_pham INTEGER NOT NULL,
    so_luong INTEGER NOT NULL,
    don_gia_luc_mua NUMERIC(18, 2) NOT NULL,
    thanh_tien NUMERIC(18, 2) NOT NULL,
    CONSTRAINT fk_chi_tiet_don_hang_don_hang FOREIGN KEY (ma_don_hang) REFERENCES don_hang (ma_don_hang) ON DELETE CASCADE,
    CONSTRAINT fk_chi_tiet_don_hang_san_pham FOREIGN KEY (ma_san_pham) REFERENCES san_pham (ma_san_pham)
);

CREATE TABLE giao_dich_thanh_toan (
    ma_giao_dich INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_don_hang INTEGER NOT NULL,
    ma_giao_dich_momo VARCHAR(100),
    phuong_thuc VARCHAR(20) NOT NULL,
    so_tien NUMERIC(18, 2) NOT NULL,
    trang_thai VARCHAR(50) NOT NULL DEFAULT 'Pending',
    noi_dung_loi VARCHAR(255),
    ngay_tao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_giao_dich_thanh_toan_don_hang FOREIGN KEY (ma_don_hang) REFERENCES don_hang (ma_don_hang) ON DELETE CASCADE
);

CREATE TABLE nhat_ky_hoat_dong (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hanh_dong VARCHAR(50) NOT NULL,
    mo_ta TEXT NOT NULL,
    ma_nhan_vien INTEGER,
    thoi_gian TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_thuc_hien VARCHAR(50),
    CONSTRAINT fk_nhat_ky_hoat_dong_nhan_vien FOREIGN KEY (ma_nhan_vien) REFERENCES nhan_vien (ma_nhan_vien) ON DELETE SET NULL
);

CREATE TABLE phien_chat (
    ma_phien INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_khach_hang INTEGER NOT NULL,
    thoi_gian_cap_nhat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_phien_chat_khach_hang FOREIGN KEY (ma_khach_hang) REFERENCES khach_hang (ma_khach_hang) ON DELETE CASCADE
);

CREATE TABLE chi_tiet_phien_chat (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_phien INTEGER NOT NULL,
    cau_hoi TEXT NOT NULL,
    cau_tra_loi TEXT NOT NULL,
    thoi_gian TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chi_tiet_phien_chat_phien_chat FOREIGN KEY (ma_phien) REFERENCES phien_chat (ma_phien) ON DELETE CASCADE
);

CREATE INDEX ix_otp_log_email_thoi_gian_tao ON otp_log (email, thoi_gian_tao DESC);
CREATE INDEX ix_so_dia_chi_ma_khach_hang ON so_dia_chi (ma_khach_hang);
CREATE INDEX ix_hinh_anh_san_pham_ma_san_pham ON hinh_anh_san_pham (ma_san_pham);
CREATE INDEX ix_thong_so_ky_thuat_ma_san_pham ON thong_so_ky_thuat (ma_san_pham);
CREATE INDEX ix_chi_tiet_phieu_nhap_ma_phieu_nhap ON chi_tiet_phieu_nhap (ma_phieu_nhap);
CREATE INDEX ix_khuyen_mai_khach_hang_ma_khach_hang ON khuyen_mai_khach_hang (ma_khach_hang);
CREATE INDEX ix_chi_tiet_gio_hang_ma_gio_hang ON chi_tiet_gio_hang (ma_gio_hang);
CREATE INDEX ix_don_hang_ma_khach_hang ON don_hang (ma_khach_hang);
CREATE INDEX ix_chi_tiet_don_hang_ma_don_hang ON chi_tiet_don_hang (ma_don_hang);
CREATE INDEX ix_giao_dich_thanh_toan_ma_don_hang ON giao_dich_thanh_toan (ma_don_hang);
CREATE INDEX ix_phien_chat_ma_khach_hang ON phien_chat (ma_khach_hang);
CREATE INDEX ix_chi_tiet_phien_chat_ma_phien ON chi_tiet_phien_chat (ma_phien);

INSERT INTO vai_tro (ten_vai_tro, mo_ta)
VALUES
    ('Admin', 'Quan tri he thong'),
    ('NhanVien', 'Nhan vien van hanh tong hop'),
    ('Staff', 'Nhan vien xu ly don hang'),
    ('Kho', 'Nhan vien kho'),
    ('Sales', 'Nhan vien ban hang')
ON CONFLICT (ten_vai_tro) DO NOTHING;

CREATE OR REPLACE FUNCTION fn_tu_dong_het_han_otp_cu()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE otp_log
    SET trang_thai = 'HetHan'
    WHERE email = NEW.email
      AND ma_log <> NEW.ma_log
      AND trang_thai = 'ConHan';
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_tu_dong_het_han_otp_cu
AFTER INSERT ON otp_log
FOR EACH ROW
EXECUTE FUNCTION fn_tu_dong_het_han_otp_cu();

CREATE OR REPLACE FUNCTION fn_cap_nhat_ton_kho_nhap_hang()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE san_pham
        SET so_luong_ton = so_luong_ton + NEW.so_luong_nhap,
            gia_ban = NEW.gia_nhap * 1.2
        WHERE ma_san_pham = NEW.ma_san_pham;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE san_pham
        SET so_luong_ton = so_luong_ton - OLD.so_luong_nhap
        WHERE ma_san_pham = OLD.ma_san_pham;
        RETURN OLD;
    ELSE
        UPDATE san_pham
        SET so_luong_ton = so_luong_ton + (NEW.so_luong_nhap - OLD.so_luong_nhap),
            gia_ban = NEW.gia_nhap * 1.2
        WHERE ma_san_pham = NEW.ma_san_pham;
        RETURN NEW;
    END IF;
END;
$$;

CREATE TRIGGER trg_cap_nhat_ton_kho_nhap_hang
AFTER INSERT OR UPDATE OR DELETE ON chi_tiet_phieu_nhap
FOR EACH ROW
EXECUTE FUNCTION fn_cap_nhat_ton_kho_nhap_hang();

CREATE OR REPLACE FUNCTION fn_cap_nhat_ton_kho_ban_hang()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_so_luong_ton INTEGER;
BEGIN
    SELECT so_luong_ton
    INTO v_so_luong_ton
    FROM san_pham
    WHERE ma_san_pham = NEW.ma_san_pham
    FOR UPDATE;

    IF v_so_luong_ton IS NULL THEN
        RAISE EXCEPTION 'San pham % khong ton tai', NEW.ma_san_pham;
    END IF;

    IF v_so_luong_ton < NEW.so_luong THEN
        RAISE EXCEPTION 'Loi: San pham trong kho khong du de thuc hien don hang nay!';
    END IF;

    UPDATE san_pham
    SET so_luong_ton = so_luong_ton - NEW.so_luong
    WHERE ma_san_pham = NEW.ma_san_pham;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_cap_nhat_ton_kho_ban_hang
BEFORE INSERT ON chi_tiet_don_hang
FOR EACH ROW
EXECUTE FUNCTION fn_cap_nhat_ton_kho_ban_hang();

CREATE OR REPLACE FUNCTION fn_tinh_tong_tien_don_hang()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_ma_don_hang INTEGER;
BEGIN
    v_ma_don_hang := COALESCE(NEW.ma_don_hang, OLD.ma_don_hang);

    UPDATE don_hang
    SET tong_tien = COALESCE((
        SELECT SUM(thanh_tien)
        FROM chi_tiet_don_hang
        WHERE ma_don_hang = v_ma_don_hang
    ), 0) + COALESCE(phi_van_chuyen, 0)
    WHERE ma_don_hang = v_ma_don_hang;

    RETURN COALESCE(NEW, OLD);
END;
$$;

CREATE TRIGGER trg_tinh_tong_tien_don_hang
AFTER INSERT OR UPDATE OR DELETE ON chi_tiet_don_hang
FOR EACH ROW
EXECUTE FUNCTION fn_tinh_tong_tien_don_hang();

CREATE OR REPLACE PROCEDURE sp_dang_ky_khach_hang(
    IN p_ten_dang_nhap VARCHAR(50),
    IN p_mat_khau_hash VARCHAR(255),
    IN p_email VARCHAR(100),
    IN p_ho_ten VARCHAR(100),
    IN p_so_dien_thoai VARCHAR(15)
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_ma_tai_khoan INTEGER;
    v_ma_khach_hang INTEGER;
BEGIN
    INSERT INTO tai_khoan (ten_dang_nhap, mat_khau_hash, email, trang_thai)
    VALUES (p_ten_dang_nhap, p_mat_khau_hash, p_email, 'Active')
    RETURNING ma_tai_khoan INTO v_ma_tai_khoan;

    INSERT INTO khach_hang (ho_ten, so_dien_thoai, email, ma_tai_khoan)
    VALUES (p_ho_ten, p_so_dien_thoai, p_email, v_ma_tai_khoan)
    RETURNING ma_khach_hang INTO v_ma_khach_hang;

    INSERT INTO gio_hang (ma_khach_hang) VALUES (v_ma_khach_hang);
END;
$$;

CREATE OR REPLACE PROCEDURE sp_them_vao_gio_hang(
    IN p_ma_khach_hang INTEGER,
    IN p_ma_san_pham INTEGER,
    IN p_so_luong INTEGER
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_ma_gio_hang INTEGER;
BEGIN
    SELECT ma_gio_hang
    INTO v_ma_gio_hang
    FROM gio_hang
    WHERE ma_khach_hang = p_ma_khach_hang;

    IF v_ma_gio_hang IS NULL THEN
        RAISE EXCEPTION 'Khach hang chua co gio hang!';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM chi_tiet_gio_hang
        WHERE ma_gio_hang = v_ma_gio_hang
          AND ma_san_pham = p_ma_san_pham
    ) THEN
        INSERT INTO chi_tiet_gio_hang (ma_gio_hang, ma_san_pham, so_luong)
        VALUES (v_ma_gio_hang, p_ma_san_pham, p_so_luong);
    ELSE
        UPDATE chi_tiet_gio_hang
        SET so_luong = so_luong + p_so_luong
        WHERE ma_gio_hang = v_ma_gio_hang
          AND ma_san_pham = p_ma_san_pham;
    END IF;
END;
$$;

CREATE OR REPLACE PROCEDURE sp_tao_don_hang(
    IN p_ma_khach_hang INTEGER,
    IN p_ma_code_don_hang VARCHAR(50),
    IN p_dia_chi_giao VARCHAR(255),
    IN p_sdt_giao VARCHAR(15),
    IN p_nguoi_nhan VARCHAR(100),
    IN p_phuong_thuc_thanh_toan VARCHAR(20),
    IN p_ma_khuyen_mai_id INTEGER DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_ma_don_hang INTEGER;
    v_ma_gio_hang INTEGER;
BEGIN
    INSERT INTO don_hang (
        ma_code_don_hang,
        ma_khach_hang,
        ngay_dat,
        tong_tien,
        trang_thai,
        phuong_thuc_thanh_toan,
        dia_chi_giao_hang,
        so_dien_thoai_giao,
        nguoi_nhan
    )
    VALUES (
        p_ma_code_don_hang,
        p_ma_khach_hang,
        CURRENT_TIMESTAMP,
        0,
        'ChoXacNhan',
        p_phuong_thuc_thanh_toan,
        p_dia_chi_giao,
        p_sdt_giao,
        p_nguoi_nhan
    )
    RETURNING ma_don_hang INTO v_ma_don_hang;

    SELECT ma_gio_hang
    INTO v_ma_gio_hang
    FROM gio_hang
    WHERE ma_khach_hang = p_ma_khach_hang;

    INSERT INTO chi_tiet_don_hang (ma_don_hang, ma_san_pham, so_luong, don_gia_luc_mua, thanh_tien)
    SELECT
        v_ma_don_hang,
        ct.ma_san_pham,
        ct.so_luong,
        sp.gia_ban,
        (ct.so_luong * sp.gia_ban)
    FROM chi_tiet_gio_hang ct
    JOIN san_pham sp ON sp.ma_san_pham = ct.ma_san_pham
    WHERE ct.ma_gio_hang = v_ma_gio_hang;

    INSERT INTO giao_dich_thanh_toan (ma_don_hang, phuong_thuc, so_tien, trang_thai)
    VALUES (v_ma_don_hang, p_phuong_thuc_thanh_toan, 0, 'Pending');

    IF p_ma_khuyen_mai_id IS NOT NULL THEN
        UPDATE khuyen_mai_khach_hang
        SET da_su_dung = TRUE
        WHERE ma_khach_hang = p_ma_khach_hang
          AND ma_khuyen_mai = p_ma_khuyen_mai_id;
    END IF;

    DELETE FROM chi_tiet_gio_hang WHERE ma_gio_hang = v_ma_gio_hang;
END;
$$;

CREATE OR REPLACE FUNCTION fn_tinh_luong_nhan_vien(
    p_thang INTEGER,
    p_nam INTEGER
)
RETURNS TABLE (
    ma_nhan_vien INTEGER,
    ho_ten VARCHAR(100),
    ten_vai_tro VARCHAR(50),
    so_don_ban_duoc BIGINT,
    so_phieu_nhap BIGINT,
    luong_tam_tinh NUMERIC(18, 2)
)
LANGUAGE sql
AS $$
    SELECT
        nv.ma_nhan_vien,
        nv.ho_ten,
        vt.ten_vai_tro,
        (
            SELECT COUNT(*)
            FROM don_hang dh
            WHERE dh.ma_nhan_vien_duyet = nv.ma_nhan_vien
              AND EXTRACT(MONTH FROM dh.ngay_dat) = p_thang
              AND EXTRACT(YEAR FROM dh.ngay_dat) = p_nam
              AND dh.trang_thai = 'DaGiao'
        ) AS so_don_ban_duoc,
        (
            SELECT COUNT(*)
            FROM phieu_nhap pn
            WHERE pn.ma_nhan_vien_nhap = nv.ma_nhan_vien
              AND EXTRACT(MONTH FROM pn.ngay_nhap) = p_thang
              AND EXTRACT(YEAR FROM pn.ngay_nhap) = p_nam
        ) AS so_phieu_nhap,
        CASE
            WHEN vt.ten_vai_tro ILIKE '%Sales%' THEN
                5000000 + (
                    (
                        SELECT COUNT(*)
                        FROM don_hang dh
                        WHERE dh.ma_nhan_vien_duyet = nv.ma_nhan_vien
                          AND EXTRACT(MONTH FROM dh.ngay_dat) = p_thang
                          AND EXTRACT(YEAR FROM dh.ngay_dat) = p_nam
                          AND dh.trang_thai = 'DaGiao'
                    ) * 50000
                )
            WHEN vt.ten_vai_tro ILIKE '%Kho%' OR vt.ten_vai_tro ILIKE '%Admin%' THEN
                6000000 + (
                    (
                        SELECT COUNT(*)
                        FROM phieu_nhap pn
                        WHERE pn.ma_nhan_vien_nhap = nv.ma_nhan_vien
                          AND EXTRACT(MONTH FROM pn.ngay_nhap) = p_thang
                          AND EXTRACT(YEAR FROM pn.ngay_nhap) = p_nam
                    ) * 100000
                )
            ELSE 5000000
        END::NUMERIC(18, 2) AS luong_tam_tinh
    FROM nhan_vien nv
    JOIN vai_tro vt ON vt.ma_vai_tro = nv.ma_vai_tro;
$$;
